import { useState } from "react";
import type { NextPage } from "next";
import HeaderLang from "../components/moleculs/HeaderLang/HeaderLang";
import HeaderNav from "../components/moleculs/HeaderNav/HeaderNav";
import ImageBody from "../components/moleculs/ImageBody/ImageBody";
import PokemonDetail from "../components/moleculs/PokemonDetail/PokemonDetail";
import styled from "@emotion/styled";
import { Grid, Pagination, Stack, TablePagination } from "@mui/material";
import { makeStyles } from "@mui/styles";

const DetailContainer = styled.div`
  margin-left: 142px;
  margin-right: 140px;
  background-color: #ffcb3b;
  align-items: center;
  justify-content: center;
`;

const ContainerText = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding-top: 100px;
  padding-bottom: 100px;
`;

const TextTitle = styled.span`
  font-weight: 700;
  font-size: 40px;
  line-height: 60px;
  color: #42494d;
  text-align: center;
`;

const TextFill = styled.span`
  font-weight: 400;
  font-size: 24px;
  line-height: 36px;
  color: #42494d;
  text-align: center;
`;

const TextTotal = styled.span`
  font-weight: 700;
  font-size: 20px;
  line-height: 20px;
  color: #fff;
`;

// const useStyles = makeStyles(() => ({
//   ul: {
//     "& .MuiPaginationItem-root": {
//       color: "#fff",
//     },
//   },
// }));

const useStyles = makeStyles(() => ({
  ul: {
    "& .MuiPaginationItem-root": {
      "&.MuiPagination-outlined": {
        "&.Mui-selected": {
          background: "#fff",
          color: "#E6AB09",
          // borderRadius: '50%',
        },
      },
    },
  },
  root: {
    "& > *": {
      marginTop: 10,
    },
    "& .MuiPaginationItem-icon": {
      // backgroundColor: "yellow",
      color: "#fff",
      borderColor: "#fff",
    },
    "& ul > li:not(:first-child):not(:last-child) > button:not(.Mui-selected)":
      {
        backgroundColor: "transparent",
        color: "#fff",
        borderColor: "#fff",
      },
  },
}));

// const useStyles = makeStyles((theme) => ({
//   root: {
//     "& ul > li:not(:first-child):not(:last-child) > button:not(.Mui-selected)":
//       {
//         backgroundColor: "transparent",
//         color: "#19D5C6",
//       },
//   },
// }));

const Home: NextPage = () => {
  const [rowsPerPage, setRowsPerPage] = useState(10);

  const classes = useStyles();

  return (
    <div>
      <HeaderLang />
      <HeaderNav />
      <ImageBody />

      <DetailContainer>
        <ContainerText>
          <TextTitle> PokeDex </TextTitle>
          <TextFill>All Generation Totaling</TextFill>
          <TextFill>999999 Pokemon</TextFill>
        </ContainerText>
        <Grid
          style={{
            marginLeft: "20px",
          }}
          container
          spacing={{ xs: 1, md: 3 }}
          columns={{ xs: 4, sm: 8, md: 12 }}
        >
          <Grid xs>
            <PokemonDetail />
          </Grid>
          <Grid xs>
            <PokemonDetail />
          </Grid>
          <Grid xs>
            <PokemonDetail />
          </Grid>
          <Grid xs>
            <PokemonDetail />
          </Grid>
          <Grid xs>
            <PokemonDetail />
          </Grid>
          <Grid xs>
            <PokemonDetail />
          </Grid>
        </Grid>
        <Stack
          direction="row"
          spacing={1}
          justifyContent="space-around"
          alignItems="center"
          style={{ padding: "30px" }}
        >
          <TextTotal>PerPage</TextTotal>
          <Pagination
            style={{ color: "white" }}
            count={10}
            variant="outlined"
            shape="rounded"
            color="primary"
            className={classes.root}
            classes={{ ul: classes.ul }}
          />
          <TextTotal>Total Data : 9999</TextTotal>
        </Stack>
      </DetailContainer>

      {/* <IconLang /> <h1>hahahah</h1> */}
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
